# Generated by Django 2.1.7 on 2019-03-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dataset',
            new_name='Item',
        ),
    ]
